# Generated by Django 3.2 on 2023-07-20 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_delete_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birth', models.DateField(verbose_name='Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='Gender')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='account.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
