# Generated by Django 3.2 on 2023-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('NEW', 'New'), ('LST', 'Lost'), ('ASG', 'Assigned'), ('CNT', 'Contacted'), ('USG', 'Unassigned')], default='NEW', max_length=10, verbose_name='Category'),
        ),
    ]
