# Generated by Django 3.2 on 2023-07-07 02:20

import applications.account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230706_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='accounts/images/photos/no-user-photo.png', upload_to=applications.account.utils.photo_file_name, verbose_name='Profile photo'),
        ),
    ]
